name: Shrine
description: Learn how to use Material for structure and layout.


dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.8.2
  english_words: ^3.1.0
  banner: ^0.1.3
  google_sign_in: ^3.2.2
  firebase_auth: ^0.6.2+1
  intl: ^0.15.6
  # flutter_localizations:
  #   sdk: flutter


  cupertino_icons: ^0.1.0
  shrine_images: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
      - family: NotoSans
        fonts:
          - asset: fonts/NotoSansCJKkr-Regular.ttf
          - asset: fonts/NotoSansCJKkr-Black.ttf
            weight: 900
          - asset: fonts/NotoSansCJKkr-Bold.ttf
            weight: 800
          - asset: fonts/NotoSansCJKkr-Medium.ttf
            weight: 500
          - asset: fonts/NotoSansCJKkr-DemiLight.ttf
            weight: 400
          - asset: fonts/NotoSansCJKkr-Light.ttf
            weight: 300

  uses-material-design: true
  assets:
    - images/0-0.jpeg
    - images/1-0.jpeg
    - images/2-0.jpeg
    - images/3-0.jpeg
    - images/4-0.jpeg
    - images/5-0.jpeg
    - images/6-0.jpeg
    - images/7-0.jpeg
    - assets/login_logo.png